spring.application.name=demo
spring.datasource.url=jdbc:h2:file:./data/inventory
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.security.oauth2.client.registration.github.client-id=YOUR_CLIENTID_HERE
spring.security.oauth2.client.registration.github.client-secret=YOUR_CLIENTSECRET_HERE
spring.security.oauth2.client.registration.github.scope=read:user