spring.application.name=demo

# H2 File Database Configuration
spring.datasource.url=jdbc:h2:file:./data/inventory
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=[your database username]
spring.datasource.password=[your database password]

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#H2 Console
spring.h2.console.enabled=true

# Thymeleaf Template Engine
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# OAuth2 Github Login
spring.security.oauth2.client.registration.github.client-id=YOUR_CLIENTID_HERE
spring.security.oauth2.client.registration.github.client-secret=YOUR_CLIENTSECRET_HERE
spring.security.oauth2.client.registration.github.scope=read:user

# Actuator & Logging
management.endpoints.web.exposure.include=health,info
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{username}] [%X{method}] [%X{uri}] %-5level %logger{36} - %msg%n

# Compression
server.compression.enabled=true
server.compression.mime-types=application/json
server.compression.min-response-size=1024